# -*- coding: utf-8 -*-
"""Lifestyle Factors Affecting Sleep Quality.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1enrBg4NqfxjHliN-xMhl6zjg7SWxPRTB

#**Lifestyle Factors Affecting Sleep Quality**
"""

import pandas as pd
df = pd.read_csv("Sleep_health_and_lifestyle_dataset.csv")

df.head()

df.shape

df.info()

df.describe()

df.columns

df.columns = df.columns.str.strip().str.replace(" ", "_")
df.columns

df.isnull().sum()

df["Sleep_Disorder"] = df["Sleep_Disorder"].fillna("None")
df.isnull().sum()

"""###Question 1: Does sleep duration affect sleep quality?

In this analysis, we examine the relationship between the number of hours a person sleeps and their reported sleep quality.

"""

df[["Sleep_Duration", "Quality_of_Sleep"]].corr()

import matplotlib.pyplot as plt

plt.figure()
plt.scatter(df["Sleep_Duration"], df["Quality_of_Sleep"])
plt.xlabel("Sleep Duration (hours)")
plt.ylabel("Sleep Quality")
plt.title("Sleep Duration vs Sleep Quality")
plt.show()

"""### Observation: Sleep Duration vs Sleep Quality

From the scatter plot and correlation, we observe a positive relationship between sleep duration and sleep quality. Individuals who sleep longer tend to report better sleep quality.

### Question 2: How does stress level impact sleep duration?

Stress is often linked to lifestyle factors such as screen exposure and social media usage. This analysis explores whether higher stress levels are associated with reduced sleep duration.
"""

df[["Stress_Level", "Sleep_Duration"]].corr()

plt.figure()
plt.scatter(df["Stress_Level"], df["Sleep_Duration"])
plt.xlabel("Stress Level")
plt.ylabel("Sleep Duration (hours)")
plt.title("Stress Level vs Sleep Duration")
plt.show()

"""### Observation: Stress Level vs Sleep Duration

The scatter plot shows a negative relationship: higher stress levels are associated with lower sleep duration. This indicates that stress may reduce the amount of sleep a person gets.

### Question: Does physical activity affect sleep duration?

We analyze whether individuals who are more physically active tend to sleep longer. This helps understand the relationship between lifestyle and sleep.
"""

df[["Physical_Activity_Level", "Sleep_Duration"]].corr()

plt.figure()
plt.scatter(df["Physical_Activity_Level"], df["Sleep_Duration"], color='green')
plt.xlabel("Physical Activity Level")
plt.ylabel("Sleep Duration (hours)")
plt.title("Physical Activity vs Sleep Duration")
plt.show()

"""### Observation: Physical Activity vs Sleep Duration

From the scatter plot and correlation, we observe that individuals with higher physical activity levels tend to have slightly longer sleep duration. This suggests that an active lifestyle may positively influence sleep patterns.

### Question: Does BMI category affect sleep quality?

We explore whether a person's BMI category (underweight, normal, overweight, obese) is associated with their sleep quality. This helps understand the link between body health and sleep patterns.
"""

import seaborn as sns

plt.figure(figsize=(8,5))
sns.countplot(x="BMI_Category", hue="Quality_of_Sleep", data=df)
plt.title("BMI Category vs Sleep Quality")
plt.xlabel("BMI Category")
plt.ylabel("Count")
plt.show()

"""### Observation: BMI Category vs Sleep Quality

The plot shows that individuals in certain BMI categories tend to report poorer sleep quality more frequently. This indicates that body health may influence sleep patterns.

### Question: How do sleep disorders affect sleep duration?

We investigate whether individuals with reported sleep disorders have shorter sleep duration compared to those without disorders.
"""

plt.figure(figsize=(8,5))
sns.boxplot(x="Sleep_Disorder", y="Sleep_Duration", data=df)
plt.title("Sleep Disorder vs Sleep Duration")
plt.xlabel("Sleep Disorder")
plt.ylabel("Sleep Duration (hours)")
plt.xticks(rotation=45)
plt.show()

"""### Observation: Sleep Disorder vs Sleep Duration

The boxplot shows that individuals with sleep disorders generally sleep fewer hours compared to those without disorders. This confirms that sleep disorders negatively impact sleep duration.

#**FINAL INSIGHTS**

1. **Sleep Duration vs Sleep Quality:** Longer sleep correlates with better sleep quality.
2. **Stress Level vs Sleep Duration:** Higher stress levels are associated with shorter sleep duration.
3. **Physical Activity vs Sleep Duration:** Individuals with higher physical activity tend to sleep slightly longer.
4. **BMI Category vs Sleep Quality:** Certain BMI categories are more likely to report poor sleep.
5. **Sleep Disorder vs Sleep Duration:** People with sleep disorders sleep fewer hours on average.

**Overall:** Lifestyle factors such as stress, physical activity, BMI, and sleep disorders significantly affect sleep patterns. Promoting a healthy lifestyle can help improve sleep quality.
"""